# Generated by Django 4.1.4 on 2022-12-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='db123',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField()),
                ('ename', models.CharField(max_length=35)),
                ('esal', models.IntegerField()),
                ('eaddr', models.TextField()),
            ],
        ),
    ]
